### PR TITLE
Rebase alpa-tensorflow onto TF associated with jax 0.4.6 (2aaeef25361311b21b9e81e992edff94bcb6bae3)

### PR DESCRIPTION
**Pull request by yhtang**
WIP

### CODE REVIEW

**Comment by GHGmc2** [comment]
jax had switched to use OpenXLA repo instead of TensorFlow: https://github.com/google/jax/commit/172a831219aa7d3524c0c8b5779dc29597a05810

**Comment by yhtang** [comment]
> jax had switched to use OpenXLA repo instead of TensorFlow: [google/jax@172a831](https://github.com/google/jax/commit/172a831219aa7d3524c0c8b5779dc29597a05810)

Thanks for bringing it up :) I'm aware of the change. Since it happened after JAX 0.4.6 while 0.4.7 is not released yet, the current plan is to first rebase to 0.4.6 and then to take care of the OpenXLA switch in the next rebase.

**Comment by GHGmc2** [comment]
> > jax had switched to use OpenXLA repo instead of TensorFlow: [google/jax@172a831](https://github.com/google/jax/commit/172a831219aa7d3524c0c8b5779dc29597a05810)
> 
> Thanks for bringing it up :) I'm aware of the change. Since it happened after JAX 0.4.6 while 0.4.7 is not released yet, the current plan is to first rebase to 0.4.6 and then to take care of the OpenXLA switch in the next rebase.

jax v0.4.7 has just released: https://github.com/google/jax/tags

**Comment by chaokunyang** [comment]
Awesome work! Since jax already switch to openxla, will we switch to openxla in this PR or do it in another PR?

**Comment by nouiz** [comment]
It will be in a follow up rebase.

**Pull request merged**
